articles/urls.py
from django.urls import path
from .views import *

app_name = 'articles'

urlpatterns = [
    path('', home, name='home'),
    path('blog/', blog, name='blog'),
    path('blog-single/<int:pk>', blog_single, name='blog-single'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('contact/', include('contact.urls', namespace='contact')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

contact/urls.py
from django.urls import path
from .views import *

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact'),
    path('about/', about, name='about'),
]

articles/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Tag(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return self.tag


class Category(models.Model):
    category = models.CharField(max_length=255)

    def __str__(self):
        return self.category


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='articles')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    author_name = models.CharField(max_length=255)
    avatar = models.ImageField(upload_to='authors')
    author_comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    avatar = models.ImageField(upload_to='comments')
    website = models.URLField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/models.py
from django.db import models


# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=255)
    avatar = models.ImageField(upload_to='team')
    profession = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

articles/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['article']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

articles/views.py
from django.shortcuts import render
from .models import *
from .forms import CommentForm


# Create your views here.

def home(request):
    articles = Article.objects.order_by('-id')
    ctx = {
        'articles': articles,
    }
    return render(request, 'index.html', ctx)


def blog(request):
    articles = Article.objects.order_by('-id')
    s = request.GET.get('s')
    if s:
        articles = articles.filter(title__icontains=s)
    cat = request.GET.get('cat')
    if cat:
        articles = articles.filter(category__category__exact=cat)
    tag = request.GET.get('tag')
    if tag:
        articles = articles.filter(tags__tag__exact=tag)
    ctx = {
        'articles': articles,
    }
    return render(request, 'blog.html', ctx)


def blog_single(request, pk):
    article = Article.objects.get(id=pk)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    articles = Article.objects.order_by('-id')
    form = CommentForm(request.POST or None, request.FILES)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.article = article
        comment.save()
    ctx = {
        'article': article,
        'categories': categories,
        'tags': tags,
        'last_articles': articles[:3],
        'form': form
    }
    return render(request, 'blog-single.html', ctx)

contact/views.py
from django.shortcuts import render
from .forms import ContactForm
from .models import *

# Create your views here.


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
    ctx = {
        'form': form
    }
    return render(request, 'contact.html', ctx)


def about(request):
    teams = Team.objects.all()
    ctx = {
        'teams': teams
    }
    return render(request, 'about.html', ctx)

templates/base.html
{% load static %}
{% load latest_articles %}
{% last_articles as latest_articles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Readit - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet"
          href="{% static 'css/A.open-iconic-bootstrap.min.css+animate.css+owl.carousel.min.css+owl.theme.default.min.css+magnific-popup.css+aos.css+ionicons.min.css+flaticon.css+icomoon.css+style.css,Mcc.7T2NDtE2fE.css' %}"/>
    <script nonce="4fa40ec1-677b-4a9c-96b8-6249c6fdc4ff">(function (w, d) {
        !function (a, e, t, r) {
            a.zarazData = a.zarazData || {}, a.zarazData.executed = [], a.zaraz = {deferred: []}, a.zaraz.q = [], a.zaraz._f = function (e) {
                return function () {
                    var t = Array.prototype.slice.call(arguments);
                    a.zaraz.q.push({m: e, a: t})
                }
            };
            for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e);
            a.addEventListener("DOMContentLoaded", (() => {
                var t = e.getElementsByTagName(r)[0], z = e.createElement(r), n = e.getElementsByTagName("title")[0];
                for (n && (a.zarazData.t = e.getElementsByTagName("title")[0].text), a.zarazData.x = Math.random(), a.zarazData.w = a.screen.width, a.zarazData.h = a.screen.height, a.zarazData.j = a.innerHeight, a.zarazData.e = a.innerWidth, a.zarazData.l = a.location.href, a.zarazData.r = e.referrer, a.zarazData.k = a.screen.colorDepth, a.zarazData.n = e.characterSet, a.zarazData.o = (new Date).getTimezoneOffset(), a.zarazData.q = []; a.zaraz.q.length;) {
                    const e = a.zaraz.q.shift();
                    a.zarazData.q.push(e)
                }
                z.defer = !0;
                for (const e of [localStorage, sessionStorage]) Object.keys(e).filter((a => a.startsWith("_zaraz_"))).forEach((t => {
                    try {
                        a.zarazData["z_" + t.slice(7)] = JSON.parse(e.getItem(t))
                    } catch {
                        a.zarazData["z_" + t.slice(7)] = e.getItem(t)
                    }
                }));
                z.referrerPolicy = "origin", z.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData))), t.parentNode.insertBefore(z, t)
            }))
        }(w, d, 0, "script");
    })(window, document);</script>
</head>
<body>
<nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="/">Read<i>it</i>.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="/" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'articles:blog' %}" class="nav-link">Articles</a></li>
                <li class="nav-item"><a href="{% url 'contact:about' %}" class="nav-link">Team</a></li>
                <li class="nav-item"><a href="{% url 'contact:contact' %}" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

<footer class="ftco-footer ftco-bg-dark ftco-section" id="footer">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="logo"><a href="/">Read<span>it</span>.</a></h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.instagram.com/ravshan.giyosov/"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">latest News</h2>
                    {% for latest_article in latest_articles %}
                        <div class="block-21 mb-4 d-flex">
                        <a class="img mr-4 rounded" style="background-image: url({{ latest_article.image.url }});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="{% url 'articles:blog-single' latest_article.id %}">{{ latest_article.title|slice:'100'}}</a></h3>
                            <div class="meta">
                                <div><a>{{ latest_article.created_at }}</a></div>
                                <div><a>{{ latest_article.author }}</a></div>
                                <div><a>{{ latest_article.comment_set.count }}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="/" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Home</a></li>
                        <li><a href="{% url 'contact:about' %}" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>About</a></li>
                        <li><a href="{% url 'articles:blog' %}" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Articles</a></li>
                        <li><a href="{% url 'contact:contact' %}" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span
                                    class="__cf_email__" data-cfemail="a3cacdc5cce3daccd6d1c7cccec2cacd8dc0ccce">[email&#160;protected]</span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                        href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js+popper.min.js+bootstrap.min.js.pagespeed.jc.RBFfyp-nte.js' %}"></script>
<script>eval(mod_pagespeed_qcL_6881BX);</script>
<script>eval(mod_pagespeed_ydsl4cdfHa);</script>
<script>eval(mod_pagespeed_OFxX3c850J);</script>
<script src="{% static 'js/jquery.easing.1.3.js+jquery.waypoints.min.js+jquery.stellar.min.js+owl.carousel.min.js.pagespeed.jc.JPoq4oqrbk.js' %}"></script>
<script>eval(mod_pagespeed_RrJrXcA2BN);</script>
<script>eval(mod_pagespeed_iReT0fckTI);</script>
<script>eval(mod_pagespeed_1pBzn$onrS);</script>
<script>eval(mod_pagespeed_ybtqMEoT_m);</script>
<script src="{% static 'js/jquery.magnific-popup.min.js+aos.js+jquery.animateNumber.min.js+scrollax.min.js+google-map.js+main.js.pagespeed.jc.aUmw5lFzKm.js' %}"></script>
<script>eval(mod_pagespeed_Pz3mrJ_63m);</script>
<script>eval(mod_pagespeed_W6d3NjFla2);</script>
<script>eval(mod_pagespeed_QjqI0dlp4G);</script>
<script>eval(mod_pagespeed_vv5V0CCUE2);</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script>eval(mod_pagespeed_LeCa8CcN8X);</script>
<script>eval(mod_pagespeed_dSHmgkmKhk);</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
        integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
        data-cf-beacon='{"rayId":"7161e66ebd51b415","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.12.0","si":100}'
        crossorigin="anonymous"></script>
</body>
</html>

templates/blog-single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="hero-wrap hero-wrap-2 js-fullheight"
         style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.7wX3e-PeJV.jpg' %})" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Blog Single</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="/blog/">Blog <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <p class="mb-5">
                    <img src="{{ article.image.url }}" alt="" class="img-fluid">
                </p>
                <h2 class="mb-3">{{ article.title }}</h2>
                <p>{{ article.content }}</p>
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tag in article.tags.all %}
                            <a href="#" class="tag-cloud-link">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img src="{{ article.avatar.url }}" alt="Image placeholder"
                             class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>{{ article.author_name }}</h3>
                        <p>{{ article.author_comment }}</p>
                    </div>
                </div>
                <div class="pt-5 mt-5">
                    <h3 class="mb-5">{{ article.comment_set.count }} Comments</h3>
                    <ul class="comment-list">
                        {% for comment in article.comment_set.all %}
                            <li class="comment">
                            <div class="vcard bio">
                                <img src="{{ comment.avatar.url }}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.name }}</h3>
                                <div class="meta mb-3">{{ comment.created_at }}</div>
                                <p>{{ comment.message }}</p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" class="p-5 bg-light" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name *</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                <label for="website">Image</label>
                                {{ form.avatar }}
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                {{ form.website }}
                            </div>
                            <div class="form-group">
                                <label for="message">Message</label>
                                {{ form.message }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
                <div class="sidebar-box">
                    <form method="get" class="search-form" action="/blog/">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="search" name="s" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <div class="categories">
                        <h3>Categories</h3>
                        {% for category in categories %}
                            <li><a href="/blog/?cat={{ category }}">{{ category }} <span class="ion-ios-arrow-forward"></span></a></li>
                        {% endfor %}
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blog</h3>
                    {% for last_article in last_articles %}
                        <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{ last_article.image.url }});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="{% url 'articles:blog-single' article.id %}">{{ last_article.title|slice:'100' }}</a></h3>
                            <div class="meta">
                                <div><a><span class="icon-calendar"></span> {{ last_article.created_at }}</a></div>
                                <div><a><span class="icon-person"></span> {{ last_article.author }}</a></div>
                                <div><a><span class="icon-chat"></span> {{ last_article.comment_set.count }}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                            <a href="/blog/?tag={{ tag }}" class="tag-cloud-link">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus
                        voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                        similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="hero-wrap js-fullheight" style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.7wX3e-PeJV.jpg' %})"
     data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
             data-scrollax-parent="true">
            <div class="col-md-12 ftco-animate">
                <h2 class="subheading">Hello! Welcome to</h2>
                <h1 class="mb-4 mb-md-0">Readit blog</h1>
                <div class="row">
                    <div class="col-md-7">
                        <div class="text">
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                                there live the blind texts. Separated they live in Bookmarksgrove right at the coast of
                                the Semantics, a large language ocean.</p>
                            <div class="mouse">
                                <a href="#" class="mouse-icon">
                                    <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section bg-light">
    <div class="container">
        <div class="row d-flex">
            {% for article in articles %}
                <div class="col-md-4 d-flex ftco-animate">
                <div class="blog-entry justify-content-end">
                    <a href="{% url 'articles:blog-single' article.id %}" class="block-20" style="background-image: url({{ article.image.url }});">
                    </a>
                    <div class="text p-4 float-right d-block">
                        <div class="topper d-flex align-items-center">
                            <div class="one py-2 pl-3 pr-1 align-self-stretch">
                                <span class="day">{{ article.created_at.day }}</span>
                            </div>
                            <div class="two pl-0 pr-3 py-2 align-self-stretch">
                                <span class="yr">{{ article.created_at.year }}</span>
                                <span class="mos">{{ article.created_at|date:'F' }}</span>
                            </div>
                        </div>
                        <h3 class="heading mb-3"><a href="{% url 'articles:blog-single' article.id %}">{{ article.title }}</a></h3>
                        <p>{{ article.content|slice:'150'}}</p>
                        <p><a href="{% url 'articles:blog-single' article.id %}" class="btn-custom"><span class="ion-ios-arrow-round-forward mr-3"></span>Read
                            more</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        <li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
     data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
             data-scrollax-parent="true">
            <div class="col-md-12 ftco-animate">
                <h2 class="subheading">Hello! Welcome to</h2>
                <h1 class="mb-4 mb-md-0">Readit blog</h1>
                <div class="row">
                    <div class="col-md-7">
                        <div class="text">
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                                there live the blind texts. Separated they live in Bookmarksgrove right at the coast of
                                the Semantics, a large language ocean.</p>
                            <div class="mouse">
                                <a href="#footer" class="mouse-icon">
                                    <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% for article in articles %}
                    <div class="case">
                    <div class="row">
                        <div class="col-md-6 col-lg-6 col-xl-8 d-flex">
                            <a href="{% url 'articles:blog-single' article.id %}" class="img w-100 mb-3 mb-md-0"
                               style="background-image: url({{ article.image.url }});"></a>
                        </div>
                        <div class="col-md-6 col-lg-6 col-xl-4 d-flex">
                            <div class="text w-100 pl-md-3">
                                <span class="subheading">{{ article.category }}</span>
                                <h2><a href="{% url 'articles:blog-single' article.id %}">{{ article.title|slice:'100'}}</a></h2>
                                <ul class="media-social list-unstyled">
                                    <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                                    <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                                    <li class="ftco-animate"><a href="https://www.instagram.com/ravshan.giyosov/"><span class="icon-instagram"></span></a></li>
                                </ul>
                                <div class="meta">
                                    <p class="mb-0"><a>{{ article.created_at }}</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        <li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}